const dataProjects = [
  {
    name: "Portafolio",
    type: "Aplicacíon Web",
    projectUrl: "/Porfolio",
    image: "/../public/assets/projects/HomePorfolio.png",
    sumamary: "Portafolio profesional Rafael Mojica",
    technologies: ["Next.js", "React.js", "Tailwind", "Javascript" ],
    backUrl: "https://github.com/RafaMojica/FRONT-Porfolio",
    frontUrl: "https://github.com/RafaMojica/FRONT-Porfolio",
    demoUrl: "/Building",
    webUrl: "/Building",
  },
  {
    name: "Watch Me",
    type: "Aplicacíon Web",
    projectUrl: "/WatchMe",
    image: "/../public/assets/projects/HomeWatchMe.png",
    sumamary: "Sitio Web enfocado de películas y series de televisión",
    technologies: ["React.js", "Redux", "Javascript", "Node.js", "Express", "Sequelize", "PostgreSQL", "Sass" ],
    backUrl: "https://github.com/RafaMojica/BACK-Web-WatchMe",
    frontUrl: "https://github.com/RafaMojica/FRONT-Web-WatchMe",
    demoUrl: "/Building",
    webUrl: "/Building",
  },
  {
    name: "RRHH",
    type: "Aplicacíon Movil",
    projectUrl: "/RRHH",
    image: "/../public/assets/projects/HomeRRHH.png",
    sumamary: "Aplicación Móvil para la dependencia de recursos Humanos",
    technologies: ["React Native", "Redux", "Javascript", "Node.js", "Express", "Sequelize", "PostgreSQL", "Material UI" ],
    backUrl: "https://github.com/RafaMojica/BACK-App-RRHH",
    frontUrl: "https://github.com/RafaMojica/FRONT-App-RRHH",
    demoUrl: "/Building",
    webUrl: "/Building",
  },
  {
    name: "Como en Casa",
    type: "Aplicacíon Web",
    projectUrl: "/ComoEnCasa",
    image: "/../public/assets/projects/HomeComoEnCasa.png",
    sumamary: "Sitio web E-commerce con temática de restaurante",
    technologies: ["React.js", "Redux", "Javascript", "Node.js", "Express", "Sequelize", "PostgreSQL", "Sass" ],
    backUrl: "https://github.com/RafaMojica/Como-en-casa/tree/main/api",
    frontUrl: "https://github.com/RafaMojica/Como-en-casa",
    demoUrl: "/Building",
    webUrl: "/Building",
  },
];

module.exports = dataProjects;
