const dataProjects = [
  {
    name: "Portafolio",
    type: "Aplicacíon Web",
    projectUrl: "/Porfolio",
    image: "/../public/assets/projects/LandpagePorfolio.png",
    sumamary: "Portafolio profesional Rafael Mojica",
    technologies: ["Next.js", "React.js", "Tailwind", "Javascript" ],
    backUrl: "/",
    frontUrl: "https://github.com/RafaMojica/FRONT-Porfolio",
    demoUrl: "/",
    webUrl: "/",
  },
  {
    name: "Whatch Me",
    type: "Aplicacíon Web",
    projectUrl: "/WhatchMe",
    image: "/../public/assets/projects/LandpageWatchMe.png",
    sumamary: "Sitio Web enfocado en peliculas y series de television",
    technologies: ["React.js", "Redux", "Javascript", "Node.js", "Express", "Sequelize", "PostgreSQL", "Sass" ],
    backUrl: "https://github.com/RafaMojica/BACK-Web-WatchMe",
    frontUrl: "https://github.com/RafaMojica/FRONT-Web-WatchMe",
    demoUrl: "/",
    webUrl: "/",
  },
  {
    name: "RRHH",
    type: "Aplicacíon Movil",
    projectUrl: "/RRHH",
    image: "/../public/assets/projects/LandpageRrhh.png",
    sumamary: "Aplicacíon Móvil para la dependencia de recursos Humanos",
    technologies: ["React Native", "Redux", "Javascript", "Node.js", "Express", "Sequelize", "PostgreSQL", "Material UI" ],
    backUrl: "https://github.com/RafaMojica/BACK-App-RRHH",
    frontUrl: "https://github.com/RafaMojica/FRONT-App-RRHH",
    demoUrl: "/",
    webUrl: "/",
  },
  {
    name: "Como en Casa",
    type: "Aplicacíon Web",
    projectUrl: "/ComoEnCasa",
    image: "/../public/assets/projects/LandpageComoEnCasa.png",
    sumamary: "Sitio web E-commerce con temática de restaurante",
    technologies: ["React.js", "Redux", "Javascript", "Node.js", "Express", "Sequelize", "PostgreSQL", "Sass" ],
    backUrl: "https://github.com/RafaMojica/Como-en-casa/tree/main/api",
    frontUrl: "https://github.com/RafaMojica/Como-en-casa",
    demoUrl: "/",
    webUrl: "/",
  },
];

module.exports = dataProjects;
